INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('neuroform-ai', 'NeuroForm AI', 'Le générateur de formulaires intelligents qui crée, teste et optimise vos formulaires en 30 secondes.', 'NeuroForm IA génère des formulaires complets à partir d''une simple description textuelle, puis les optimise en continu grâce au machine learning. Les taux de conversion sont mesurés en temps réel et l''IA propose des variantes à tester (A/B testing automatique).

Fonctionnalités clés : génération par prompt, logique conditionnelle, analyse heatmap des champs, intégration Notion / Airtable / HubSpot et export webhook. Idéal pour les SaaS, les agences et les créateurs d''audience qui veulent des formulaires qui convertissent vraiment.', 'saas', 'chariow', '["premium","nouveau"]', '14,90 €/mois', 'https://checkout.chariow.com/neuroform-pro', NULL, NULL, NULL, 'https://www.youtube.com/watch?v=1FUcniACzmc', 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/54ae361e5a6f.webp', 0, 1787760248797, 1788105848797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('pixelpeek', 'PixelPeek API', 'API de captures d''écran pixel-perfect de n''importe quelle page web, en 200 ms.', 'PixelPeek transforme n''importe quelle URL en capture d''écran haute définition via une simple requête REST. Rendu Chrome headless, émulation mobile, injection de cookies, blocage des pop-ups et attente de sélecteur avant capture.

Le plan gratuit offre 500 captures/mois sans carte bancaire. Utilisé par des équipes produit pour la veille concurrentielle, la modération de contenus et la documentation automatisée. Documentation claire, SDK JavaScript et Python inclus.', 'saas', 'chariow', '["gratuit","beta"]', 'Gratuit', 'https://checkout.chariow.com/pixelpeek-free', NULL, NULL, NULL, 'https://www.youtube.com/watch?v=Tn6-PIqc4UM', 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e5d6942c6b49.png', 0, 1785341048797, 1787241848797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('clipforge', 'ClipForge', 'Gestionnaire de presse-papiers pour développeurs : historique infini, snippets et recherche instantanée.', 'ClipForge garde en mémoire chaque élément copié (texte, code, couleurs, images) avec un historique illimité et une recherche instantanée par mot-clé ou par application source. Les snippets récurrents deviennent des modèles réutilisables avec placeholders.

Application desktop native multi-plateforme (Windows, macOS, Linux), démarrage au lancement, mode « incognito » automatique pour les mots de passe. Léger : moins de 40 Mo en RAM. Installation en une seule ligne de commande.', 'desktop', 'terminal', '["nouveau","gratuit"]', 'Gratuit', 'https://github.com/beta-arsenal/clipforge', NULL, NULL, 'curl -fsSL https://clipforge.sh/install | bash', NULL, 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/49eb45023c1e.jpg', 0, 1787501048797, 1788019448797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('termvault', 'TermVault', 'Coffre-fort de mots de passe en ligne de commande, chiffré localement, compatible teams.', 'TermVault ramène la sécurité au terminal : vos secrets sont chiffrés localement (AES-256-GCM, clé maîtresse dérivée via Argon2) puis synchronisés de bout en bout. Aucun serveur tiers n''accède à vos données en clair.

Commandes courtes (tv get, tv put, tv rotate), génération de mots de passe, injection directe dans les variables d''environnement de vos shells et CI. Le mode team permet de partager des secrets par projet avec audit des accès. Licence à vie, mises à jour incluses 1 an.', 'desktop', 'terminal', '["premium"]', '9,90 € — licence', 'https://github.com/beta-arsenal/termvault', NULL, NULL, 'npx termvault init --secure', NULL, 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/164df61d5fa8.jpg', 0, 1784131448797, 1786550648797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('reposentinel', 'RepoSentinel', 'Scanner CLI qui audite vos dépôts GitHub : secrets exposés, dépendances vulnérables, mauvaises pratiques.', 'RepoSentinel analyse vos dépôts en local avant chaque push et bloque les fuites de secrets (clés API, tokens, certificats) grâce à plus de 140 motifs de détection. Il vérifie aussi les dépendances vulnérables (CVE) et signale les fichiers trop permissifs.

Configuration zéro : détecte automatiquement les stacks (Node, Python, Go, PHP). Sortie lisible avec suggestions de correction, mode CI/CD inclus. Aucune donnée n''est envoyée en ligne — tout reste sur votre machine.', 'desktop', 'terminal', '["beta"]', 'Gratuit', 'https://github.com/beta-arsenal/reposentinel', NULL, NULL, NULL, NULL, 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ae049cb21c9e.jpg', 0, 1786464248797, 1787673848797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('hydrotrack', 'HydroTrack', 'Suivi d''hydratation gamifié : rappels intelligents, badges et widgets d''écran d''accueil.', 'HydroTrack vous aide à boire régulièrement sans y penser : objectifs personnalisés selon votre poids et votre activité, rappels adaptatifs (pas pendant vos réunions !), badges de série et animations célébrant chaque palier.

PWA ultra-légère (< 200 Ko) installable depuis n''importe quel navigateur, ou APK natif pour Android avec synchronisation offline. Le widget d''écran d''accueil affiche votre progression du jour d''un coup d''œil. 100 % gratuit, sans publicité et sans compte requis.', 'mobile', 'mobile', '["gratuit","nouveau"]', 'Gratuit', 'https://cdn.betaarsenal.dev/hydrotrack/hydrotrack-v2.3.1.apk', 'https://cdn.betaarsenal.dev/hydrotrack/hydrotrack-v2.3.1.apk', 'https://hydrotrack.betaarsenal.dev', NULL, 'https://www.tiktok.com/@drjadeofficial/video/7550286763244211478', 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e22dd04629fc.png', 0, 1787933048797, 1788192248797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('fokusflow', 'FokusFlow', 'Minuteur Pomodoro avec son ambiant génératif et statistiques de concentration profonde.', 'FokusFlow va plus loin que le simple Pomodoro : il génère des paysages sonores adaptatifs ( pluie, café, brown noise) dont l''intensité suit vos cycles de concentration, et mesure votre « temps de focus profond » réel grâce à l''analyse des interruptions.

Statistiques hebdomadaires, synchronisation multi-appareils, mode strict qui bloque les distractions pendant les sessions de travail. La version Premium débloque les scènes sonores infinies, le suivi de projets et l''export CSV. Disponible en PWA installable et en APK Android.', 'mobile', 'mobile', '["premium","nouveau"]', '4,99 €', 'https://cdn.betaarsenal.dev/fokusflow/fokusflow-v1.8.0.apk', 'https://cdn.betaarsenal.dev/fokusflow/fokusflow-v1.8.0.apk', 'https://fokusflow.betaarsenal.dev', NULL, 'https://www.youtube.com/shorts/2g6cb23U9J8', 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7afbefd162ec.png', 0, 1787241848797, 1788105848797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('dev-independant', 'Le Dev Indépendant', 'E-book de 230 pages : lancez une activité de développeur solo rentable en 90 jours.', 'La méthode complète pour passer de salarié à développeur indépendant sans y perdre : positionnement, tarification au valeur, prospection par contenu, gestion administrative (statuts, URSSAF, TVA) et automatisation de la production.

230 pages illustrées, 14 modèles prêts à l''emploi (propositions commerciales, contrats, e-mails de relance), 6 études de cas de devs français et un plan d''action jour par jour sur 90 jours. Formats PDF, ePub et Notion offerts. Mise à jour gratuite à vie.', 'ebook', 'chariow', '["premium"]', '19,90 €', 'https://checkout.chariow.com/dev-independant', NULL, NULL, NULL, 'https://www.youtube.com/watch?v=CRsOXaofPmk', 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/69cbc29afeb8.jpg', 0, 1782921848797, 1786982648797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('prompt-alchemy', 'Prompt Alchemy', 'Mini-guide gratuit : les 12 principes pour écrire des prompts qui produisent des résultats exploitables.', 'Un e-book court et dense (42 pages) qui décortique l''anatomie d''un prompt efficace : rôle, contexte, contraintes, format de sortie et exemples few-shot. Chaque principe est illustré d''un avant/après mesurable sur GPT-4, Claude et Gemini.

Inclut la checklist « Prompt-Ready » imprimable et le framework C.A.S.T. (Contexte, Action, Structure, Ton) utilisé par les équipes qui industrialisent leurs prompts. Gratuit, en français, sans inscription.', 'ebook', 'chariow', '["gratuit","nouveau"]', 'Gratuit', 'https://checkout.chariow.com/prompt-alchemy-free', NULL, NULL, NULL, NULL, 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/80d107990458.jpg', 0, 1786896248797, 1787846648797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('megapack-prompts', 'MegaPack 500 Prompts', '500 prompts testés et catégorisés pour marketing, code, design et productivité — prêts à copier.', 'Le MegaPack réunit 500 prompts professionnels testés sur des projets réels, classés en 8 catégories (SEO, copywriting, développement, design, analyse de données, e-mailing, support client, automatisation). Chaque fiche indique le modèle recommandé, les variables à personnaliser et le résultat attendu.

Livré en Notion + fichier JSON importable dans vos outils favoris (ChatGPT projets, Claude, Raycast). Mises à jour mensuelles avec les nouveaux prompts de la communauté. Licence d''équipe incluse jusqu''à 5 utilisateurs.', 'prompts', 'chariow', '["premium"]', '12,90 €', 'https://checkout.chariow.com/megapack-500', NULL, NULL, NULL, NULL, 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8c880c42cd05.png', 0, 1784822648797, 1787501048797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('flowbridge-n8n', 'FlowBridge — Pack n8n', '40 workflows n8n prêts à l''emploi : CRM, facturation, veille, publication sociale et support.', 'FlowBridge est une collection open-source de 40 workflows n8n documentés et versionnés, prêts à importer en un clic. Chaque workflow est accompagné d''un guide d''installation, des variables d''environnement attendues et d''une vidéo de démonstration.

Catégories couvertes : synchronisation CRM, relances de facturation, veille concurrentielle automatisée, publication multi-réseaux, triage du support avec réponses assistées par IA. Le dépôt est mis à jour chaque semaine par la communauté. Clonez, configurez, automatisez.', 'prompts', 'terminal', '["beta","gratuit"]', 'Gratuit', 'https://github.com/beta-arsenal/flowbridge-templates', NULL, NULL, NULL, NULL, 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c454051a78ff.jpg', 0, 1787587448797, 1788192248797);
INSERT INTO products (id, title, short_description, description, category, action_type, badges, price, action_url, apk_url, pwa_url, command, video_url, image_url, clicks, created_at, updated_at) VALUES ('zenpost', 'ZenPost', 'Planificateur social qui écrit, programme et recycle vos contenus sur 6 réseaux.', 'ZenPost centralise votre production de contenu : rédaction assistée par IA calée sur votre voix de marque, calendrier visuel, publication programmée sur X, LinkedIn, Instagram, TikTok, Bluesky et Threads, et recyclage intelligent de vos meilleurs posts.

La file d''attente « Evergreen » republie automatiquement vos contenus performants avec des variations générées. Statistiques unifiées par réseau et meilleur moment de publication calculé sur votre audience. Essai 14 jours sans carte bancaire.', 'saas', 'chariow', '["beta"]', '7,90 €/mois', 'https://checkout.chariow.com/zenpost-trial', NULL, NULL, NULL, NULL, 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ed37f985b3b9.jpg', 0, 1785945848797, 1787414648797);
INSERT INTO analytics (id, visits, actions_total, clicks_by_product, visits_by_day, recent_visits, updated_at) VALUES (1, 1256, 1114, '{"neuroform-ai":89,"pixelpeek":153,"clipforge":67,"termvault":41,"reposentinel":29,"hydrotrack":206,"fokusflow":119,"dev-independant":96,"prompt-alchemy":77,"megapack-prompts":134,"flowbridge-n8n":58,"zenpost":45}', '{"2026-09-01":185,"2026-08-31":214,"2026-08-30":196,"2026-08-29":243,"2026-08-28":268,"2026-08-27":312,"2026-08-26":287,"2026-09-02":6}', '[1788361057973]', 1788361057973);
INSERT INTO media (name, url, kind, size, uploaded_at) VALUES ('1788360734411-ob4H85hV0z9JNkQWq8j8ZVm42UDoS2ZsB4XiC23S.avif', 'https://raw.githubusercontent.com/odin10032-rgb/arsenal-data/main/uploads/1788360734411-ob4H85hV0z9JNkQWq8j8ZVm42UDoS2ZsB4XiC23S.avif', 'image', 54468, 1788360737722);
INSERT INTO media (name, url, kind, size, uploaded_at) VALUES ('ba-mtiv40vw-hxa3cn.png', '/api/media/ba-mtiv40vw-hxa3cn.png', 'image', 70, 1788278944893);
INSERT INTO media (name, url, kind, size, uploaded_at) VALUES ('ba-mtiuykwz-1a0zrm.png', '/api/media/ba-mtiuykwz-1a0zrm.png', 'image', 2340, 1788278690919);